name: Bug Report
description: File a bug report.
labels: ["T: Bugfix", "Issue: Needs Replicating", "S: Untriaged"]
type: "Bug"
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: |
      This happened!
      
      Steps to reproduce the behavior:
      1. Go to '...'
      2. Click on '....'
      3. Place down '...'
      4. See error
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version of the mod you're running?
    options:
    - 1.1.0
    - 1.2.0
    - 1.2.1
    - 1.2.2
    - 1.2.3
    - 1.2.4
    - 1.2.5
    - 1.2.6
    - 1.2.7
    default: 0
  validations:
    required: true
- type: dropdown
  id: modloader
  attributes:
    label: Mod Loader
    description: Which modloader are you using
    options:
    - fabric
    - forge
    default: 0
  validations:
    required: true
- type: input
  id: build
  attributes:
    label: Build number & branch
    description: What build are you running? Skip this question if you're not running a **BETA** build.
    placeholder: "2226-feat-boti"
- type: textarea
  attributes:
    label: Logs & screenshots
    description: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: I've checked the reported issues...
    options:
      - label: |
          ...and this issue was not reported before.
        required: true
