name: Feature Request
description: File a feature request.
labels: ["T: New feature", "S: Untriaged"]
type: "Feature"
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  id: description
  attributes:
    label: Description
    description: Tell us, what do you want to be implemented?
    placeholder: Tell us what you want!
    value: |
      I want to be able to spill the tea on the console.
  validations:
    required: true
- type: textarea
  attributes:
    label: Images, links & related resources
    description: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: I've checked the feature requests...
    options:
      - label: |
          ...and this feature request was not requested before.
        required: true
